export default {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    POINTS_INC: 'POINTS_INC',
    POINTS_DEC: 'POINTS_DEC',
    POINTS_ZERO: 'POINTS_ZERO',
    GAME_ON: 'GAME_ON',
    GAME_OFF: 'GAME_OFF',
    TIME_INC1: 'TIME_INC1',
    TIME_DEC1: 'TIME_DEC1',
    TIME_INC10: 'TIME_INC10',
    TIME_DEC10: 'TIME_DEC10',
    SET_TIME: 'SET_TIME',
    STOP_TIME: 'STOP_TIME',
    RND_SENTENCE: 'RND_SENTENCE',
    REGISTER: 'REGISTER'
}